name: Prime Cache Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prime_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: cache-b3fd683

      - name: prime-cache-b3fd683
        run: |
          echo "Cache hit result: ${{ steps.cache-step.outputs.cache-hit }}"
